### ISSUE TITLE
请问你今天还能用吗，我的那个用不了了

### ISSUE THREAD

**Issue by Panda-0129** [jetdky/I-go-to-the-library#1]
现在那边无脑返回200，但不执行操作

**Comment by jetdky** [comment]
你选座提交的时候抓个包，和用Python造的包对比一下。我这边也是昨天不能用了，抓包发现header的一些东西都变了，得修改一下才能再用。

**Comment by Panda-0129** [comment]
关键我已经修改过了，现在的情况就是我选上了位置，他还是会返回200，正常情况应该返回“您已预约其他位置”，你是怎么修改header的啊- -
